/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewInboxRouteImport } from './routes/review-inbox'
import { Route as RepositoryRouteImport } from './routes/repository'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as ActivityLogRouteImport } from './routes/activity-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DesignIndexRouteImport } from './routes/design.index'
import { Route as SettingsDelegationRouteImport } from './routes/settings.delegation'
import { Route as ExternalVerifyRouteImport } from './routes/external.verify'
import { Route as ExternalLoginRouteImport } from './routes/external.login'
import { Route as ExternalExpiredRouteImport } from './routes/external.expired'
import { Route as DocumentsNewRouteImport } from './routes/documents.new'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as DashboardDepartmentRouteImport } from './routes/dashboard.department'
import { Route as ConfigUsersRouteImport } from './routes/config.users'
import { Route as ConfigUserTypesRouteImport } from './routes/config.user-types'
import { Route as ConfigRolesRouteImport } from './routes/config.roles'
import { Route as ConfigExternalApproversRouteImport } from './routes/config.external-approvers'
import { Route as ConfigDocumentTypesRouteImport } from './routes/config.document-types'
import { Route as ConfigDirectoryRouteImport } from './routes/config.directory'
import { Route as ConfigDepartmentsRouteImport } from './routes/config.departments'
import { Route as ConfigApprovalModesRouteImport } from './routes/config.approval-modes'
import { Route as ConfigActiveDirectoryRouteImport } from './routes/config.active-directory'
import { Route as ConfigWorkflowsIndexRouteImport } from './routes/config.workflows.index'
import { Route as ExternalDocumentsTokenRouteImport } from './routes/external.documents.$token'
import { Route as DocumentsIdReviewRouteImport } from './routes/documents.$id.review'
import { Route as DocumentsIdEditRouteImport } from './routes/documents.$id.edit'
import { Route as ConfigWorkflowsNewRouteImport } from './routes/config.workflows.new'
import { Route as ConfigWorkflowsIdRouteImport } from './routes/config.workflows.$id'

const ReviewInboxRoute = ReviewInboxRouteImport.update({
  id: '/review-inbox',
  path: '/review-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRoute = RepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogRoute = ActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/design/',
  path: '/design/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDelegationRoute = SettingsDelegationRouteImport.update({
  id: '/settings/delegation',
  path: '/settings/delegation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalVerifyRoute = ExternalVerifyRouteImport.update({
  id: '/external/verify',
  path: '/external/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalLoginRoute = ExternalLoginRouteImport.update({
  id: '/external/login',
  path: '/external/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalExpiredRoute = ExternalExpiredRouteImport.update({
  id: '/external/expired',
  path: '/external/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDepartmentRoute = DashboardDepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => DashboardRoute,
} as any)
const ConfigUsersRoute = ConfigUsersRouteImport.update({
  id: '/config/users',
  path: '/config/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigUserTypesRoute = ConfigUserTypesRouteImport.update({
  id: '/config/user-types',
  path: '/config/user-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRolesRoute = ConfigRolesRouteImport.update({
  id: '/config/roles',
  path: '/config/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigExternalApproversRoute = ConfigExternalApproversRouteImport.update({
  id: '/config/external-approvers',
  path: '/config/external-approvers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigDocumentTypesRoute = ConfigDocumentTypesRouteImport.update({
  id: '/config/document-types',
  path: '/config/document-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigDirectoryRoute = ConfigDirectoryRouteImport.update({
  id: '/config/directory',
  path: '/config/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigDepartmentsRoute = ConfigDepartmentsRouteImport.update({
  id: '/config/departments',
  path: '/config/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigApprovalModesRoute = ConfigApprovalModesRouteImport.update({
  id: '/config/approval-modes',
  path: '/config/approval-modes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigActiveDirectoryRoute = ConfigActiveDirectoryRouteImport.update({
  id: '/config/active-directory',
  path: '/config/active-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigWorkflowsIndexRoute = ConfigWorkflowsIndexRouteImport.update({
  id: '/config/workflows/',
  path: '/config/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalDocumentsTokenRoute = ExternalDocumentsTokenRouteImport.update({
  id: '/external/documents/$token',
  path: '/external/documents/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdReviewRoute = DocumentsIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DocumentsIdRoute,
} as any)
const DocumentsIdEditRoute = DocumentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DocumentsIdRoute,
} as any)
const ConfigWorkflowsNewRoute = ConfigWorkflowsNewRouteImport.update({
  id: '/config/workflows/new',
  path: '/config/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigWorkflowsIdRoute = ConfigWorkflowsIdRouteImport.update({
  id: '/config/workflows/$id',
  path: '/config/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/audit-log': typeof AuditLogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/review-inbox': typeof ReviewInboxRoute
  '/config/active-directory': typeof ConfigActiveDirectoryRoute
  '/config/approval-modes': typeof ConfigApprovalModesRoute
  '/config/departments': typeof ConfigDepartmentsRoute
  '/config/directory': typeof ConfigDirectoryRoute
  '/config/document-types': typeof ConfigDocumentTypesRoute
  '/config/external-approvers': typeof ConfigExternalApproversRoute
  '/config/roles': typeof ConfigRolesRoute
  '/config/user-types': typeof ConfigUserTypesRoute
  '/config/users': typeof ConfigUsersRoute
  '/dashboard/department': typeof DashboardDepartmentRoute
  '/documents/$id': typeof DocumentsIdRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/external/expired': typeof ExternalExpiredRoute
  '/external/login': typeof ExternalLoginRoute
  '/external/verify': typeof ExternalVerifyRoute
  '/settings/delegation': typeof SettingsDelegationRoute
  '/design/': typeof DesignIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/config/workflows/$id': typeof ConfigWorkflowsIdRoute
  '/config/workflows/new': typeof ConfigWorkflowsNewRoute
  '/documents/$id/edit': typeof DocumentsIdEditRoute
  '/documents/$id/review': typeof DocumentsIdReviewRoute
  '/external/documents/$token': typeof ExternalDocumentsTokenRoute
  '/config/workflows/': typeof ConfigWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/audit-log': typeof AuditLogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/review-inbox': typeof ReviewInboxRoute
  '/config/active-directory': typeof ConfigActiveDirectoryRoute
  '/config/approval-modes': typeof ConfigApprovalModesRoute
  '/config/departments': typeof ConfigDepartmentsRoute
  '/config/directory': typeof ConfigDirectoryRoute
  '/config/document-types': typeof ConfigDocumentTypesRoute
  '/config/external-approvers': typeof ConfigExternalApproversRoute
  '/config/roles': typeof ConfigRolesRoute
  '/config/user-types': typeof ConfigUserTypesRoute
  '/config/users': typeof ConfigUsersRoute
  '/dashboard/department': typeof DashboardDepartmentRoute
  '/documents/$id': typeof DocumentsIdRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/external/expired': typeof ExternalExpiredRoute
  '/external/login': typeof ExternalLoginRoute
  '/external/verify': typeof ExternalVerifyRoute
  '/settings/delegation': typeof SettingsDelegationRoute
  '/design': typeof DesignIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/config/workflows/$id': typeof ConfigWorkflowsIdRoute
  '/config/workflows/new': typeof ConfigWorkflowsNewRoute
  '/documents/$id/edit': typeof DocumentsIdEditRoute
  '/documents/$id/review': typeof DocumentsIdReviewRoute
  '/external/documents/$token': typeof ExternalDocumentsTokenRoute
  '/config/workflows': typeof ConfigWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/audit-log': typeof AuditLogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/review-inbox': typeof ReviewInboxRoute
  '/config/active-directory': typeof ConfigActiveDirectoryRoute
  '/config/approval-modes': typeof ConfigApprovalModesRoute
  '/config/departments': typeof ConfigDepartmentsRoute
  '/config/directory': typeof ConfigDirectoryRoute
  '/config/document-types': typeof ConfigDocumentTypesRoute
  '/config/external-approvers': typeof ConfigExternalApproversRoute
  '/config/roles': typeof ConfigRolesRoute
  '/config/user-types': typeof ConfigUserTypesRoute
  '/config/users': typeof ConfigUsersRoute
  '/dashboard/department': typeof DashboardDepartmentRoute
  '/documents/$id': typeof DocumentsIdRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/external/expired': typeof ExternalExpiredRoute
  '/external/login': typeof ExternalLoginRoute
  '/external/verify': typeof ExternalVerifyRoute
  '/settings/delegation': typeof SettingsDelegationRoute
  '/design/': typeof DesignIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/config/workflows/$id': typeof ConfigWorkflowsIdRoute
  '/config/workflows/new': typeof ConfigWorkflowsNewRoute
  '/documents/$id/edit': typeof DocumentsIdEditRoute
  '/documents/$id/review': typeof DocumentsIdReviewRoute
  '/external/documents/$token': typeof ExternalDocumentsTokenRoute
  '/config/workflows/': typeof ConfigWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-log'
    | '/audit-log'
    | '/dashboard'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/repository'
    | '/review-inbox'
    | '/config/active-directory'
    | '/config/approval-modes'
    | '/config/departments'
    | '/config/directory'
    | '/config/document-types'
    | '/config/external-approvers'
    | '/config/roles'
    | '/config/user-types'
    | '/config/users'
    | '/dashboard/department'
    | '/documents/$id'
    | '/documents/new'
    | '/external/expired'
    | '/external/login'
    | '/external/verify'
    | '/settings/delegation'
    | '/design/'
    | '/documents/'
    | '/settings/'
    | '/config/workflows/$id'
    | '/config/workflows/new'
    | '/documents/$id/edit'
    | '/documents/$id/review'
    | '/external/documents/$token'
    | '/config/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-log'
    | '/audit-log'
    | '/dashboard'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/repository'
    | '/review-inbox'
    | '/config/active-directory'
    | '/config/approval-modes'
    | '/config/departments'
    | '/config/directory'
    | '/config/document-types'
    | '/config/external-approvers'
    | '/config/roles'
    | '/config/user-types'
    | '/config/users'
    | '/dashboard/department'
    | '/documents/$id'
    | '/documents/new'
    | '/external/expired'
    | '/external/login'
    | '/external/verify'
    | '/settings/delegation'
    | '/design'
    | '/documents'
    | '/settings'
    | '/config/workflows/$id'
    | '/config/workflows/new'
    | '/documents/$id/edit'
    | '/documents/$id/review'
    | '/external/documents/$token'
    | '/config/workflows'
  id:
    | '__root__'
    | '/'
    | '/activity-log'
    | '/audit-log'
    | '/dashboard'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/repository'
    | '/review-inbox'
    | '/config/active-directory'
    | '/config/approval-modes'
    | '/config/departments'
    | '/config/directory'
    | '/config/document-types'
    | '/config/external-approvers'
    | '/config/roles'
    | '/config/user-types'
    | '/config/users'
    | '/dashboard/department'
    | '/documents/$id'
    | '/documents/new'
    | '/external/expired'
    | '/external/login'
    | '/external/verify'
    | '/settings/delegation'
    | '/design/'
    | '/documents/'
    | '/settings/'
    | '/config/workflows/$id'
    | '/config/workflows/new'
    | '/documents/$id/edit'
    | '/documents/$id/review'
    | '/external/documents/$token'
    | '/config/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogRoute: typeof ActivityLogRoute
  AuditLogRoute: typeof AuditLogRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportsRoute: typeof ReportsRoute
  RepositoryRoute: typeof RepositoryRoute
  ReviewInboxRoute: typeof ReviewInboxRoute
  ConfigActiveDirectoryRoute: typeof ConfigActiveDirectoryRoute
  ConfigApprovalModesRoute: typeof ConfigApprovalModesRoute
  ConfigDepartmentsRoute: typeof ConfigDepartmentsRoute
  ConfigDirectoryRoute: typeof ConfigDirectoryRoute
  ConfigDocumentTypesRoute: typeof ConfigDocumentTypesRoute
  ConfigExternalApproversRoute: typeof ConfigExternalApproversRoute
  ConfigRolesRoute: typeof ConfigRolesRoute
  ConfigUserTypesRoute: typeof ConfigUserTypesRoute
  ConfigUsersRoute: typeof ConfigUsersRoute
  DocumentsIdRoute: typeof DocumentsIdRouteWithChildren
  DocumentsNewRoute: typeof DocumentsNewRoute
  ExternalExpiredRoute: typeof ExternalExpiredRoute
  ExternalLoginRoute: typeof ExternalLoginRoute
  ExternalVerifyRoute: typeof ExternalVerifyRoute
  SettingsDelegationRoute: typeof SettingsDelegationRoute
  DesignIndexRoute: typeof DesignIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ConfigWorkflowsIdRoute: typeof ConfigWorkflowsIdRoute
  ConfigWorkflowsNewRoute: typeof ConfigWorkflowsNewRoute
  ExternalDocumentsTokenRoute: typeof ExternalDocumentsTokenRoute
  ConfigWorkflowsIndexRoute: typeof ConfigWorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review-inbox': {
      id: '/review-inbox'
      path: '/review-inbox'
      fullPath: '/review-inbox'
      preLoaderRoute: typeof ReviewInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository': {
      id: '/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-log': {
      id: '/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof ActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/design'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/delegation': {
      id: '/settings/delegation'
      path: '/settings/delegation'
      fullPath: '/settings/delegation'
      preLoaderRoute: typeof SettingsDelegationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external/verify': {
      id: '/external/verify'
      path: '/external/verify'
      fullPath: '/external/verify'
      preLoaderRoute: typeof ExternalVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external/login': {
      id: '/external/login'
      path: '/external/login'
      fullPath: '/external/login'
      preLoaderRoute: typeof ExternalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external/expired': {
      id: '/external/expired'
      path: '/external/expired'
      fullPath: '/external/expired'
      preLoaderRoute: typeof ExternalExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/department': {
      id: '/dashboard/department'
      path: '/department'
      fullPath: '/dashboard/department'
      preLoaderRoute: typeof DashboardDepartmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/config/users': {
      id: '/config/users'
      path: '/config/users'
      fullPath: '/config/users'
      preLoaderRoute: typeof ConfigUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/user-types': {
      id: '/config/user-types'
      path: '/config/user-types'
      fullPath: '/config/user-types'
      preLoaderRoute: typeof ConfigUserTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/roles': {
      id: '/config/roles'
      path: '/config/roles'
      fullPath: '/config/roles'
      preLoaderRoute: typeof ConfigRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/external-approvers': {
      id: '/config/external-approvers'
      path: '/config/external-approvers'
      fullPath: '/config/external-approvers'
      preLoaderRoute: typeof ConfigExternalApproversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/document-types': {
      id: '/config/document-types'
      path: '/config/document-types'
      fullPath: '/config/document-types'
      preLoaderRoute: typeof ConfigDocumentTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/directory': {
      id: '/config/directory'
      path: '/config/directory'
      fullPath: '/config/directory'
      preLoaderRoute: typeof ConfigDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/departments': {
      id: '/config/departments'
      path: '/config/departments'
      fullPath: '/config/departments'
      preLoaderRoute: typeof ConfigDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/approval-modes': {
      id: '/config/approval-modes'
      path: '/config/approval-modes'
      fullPath: '/config/approval-modes'
      preLoaderRoute: typeof ConfigApprovalModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/active-directory': {
      id: '/config/active-directory'
      path: '/config/active-directory'
      fullPath: '/config/active-directory'
      preLoaderRoute: typeof ConfigActiveDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/workflows/': {
      id: '/config/workflows/'
      path: '/config/workflows'
      fullPath: '/config/workflows/'
      preLoaderRoute: typeof ConfigWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external/documents/$token': {
      id: '/external/documents/$token'
      path: '/external/documents/$token'
      fullPath: '/external/documents/$token'
      preLoaderRoute: typeof ExternalDocumentsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id/review': {
      id: '/documents/$id/review'
      path: '/review'
      fullPath: '/documents/$id/review'
      preLoaderRoute: typeof DocumentsIdReviewRouteImport
      parentRoute: typeof DocumentsIdRoute
    }
    '/documents/$id/edit': {
      id: '/documents/$id/edit'
      path: '/edit'
      fullPath: '/documents/$id/edit'
      preLoaderRoute: typeof DocumentsIdEditRouteImport
      parentRoute: typeof DocumentsIdRoute
    }
    '/config/workflows/new': {
      id: '/config/workflows/new'
      path: '/config/workflows/new'
      fullPath: '/config/workflows/new'
      preLoaderRoute: typeof ConfigWorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/workflows/$id': {
      id: '/config/workflows/$id'
      path: '/config/workflows/$id'
      fullPath: '/config/workflows/$id'
      preLoaderRoute: typeof ConfigWorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardDepartmentRoute: typeof DashboardDepartmentRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDepartmentRoute: DashboardDepartmentRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocumentsIdRouteChildren {
  DocumentsIdEditRoute: typeof DocumentsIdEditRoute
  DocumentsIdReviewRoute: typeof DocumentsIdReviewRoute
}

const DocumentsIdRouteChildren: DocumentsIdRouteChildren = {
  DocumentsIdEditRoute: DocumentsIdEditRoute,
  DocumentsIdReviewRoute: DocumentsIdReviewRoute,
}

const DocumentsIdRouteWithChildren = DocumentsIdRoute._addFileChildren(
  DocumentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogRoute: ActivityLogRoute,
  AuditLogRoute: AuditLogRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ReportsRoute: ReportsRoute,
  RepositoryRoute: RepositoryRoute,
  ReviewInboxRoute: ReviewInboxRoute,
  ConfigActiveDirectoryRoute: ConfigActiveDirectoryRoute,
  ConfigApprovalModesRoute: ConfigApprovalModesRoute,
  ConfigDepartmentsRoute: ConfigDepartmentsRoute,
  ConfigDirectoryRoute: ConfigDirectoryRoute,
  ConfigDocumentTypesRoute: ConfigDocumentTypesRoute,
  ConfigExternalApproversRoute: ConfigExternalApproversRoute,
  ConfigRolesRoute: ConfigRolesRoute,
  ConfigUserTypesRoute: ConfigUserTypesRoute,
  ConfigUsersRoute: ConfigUsersRoute,
  DocumentsIdRoute: DocumentsIdRouteWithChildren,
  DocumentsNewRoute: DocumentsNewRoute,
  ExternalExpiredRoute: ExternalExpiredRoute,
  ExternalLoginRoute: ExternalLoginRoute,
  ExternalVerifyRoute: ExternalVerifyRoute,
  SettingsDelegationRoute: SettingsDelegationRoute,
  DesignIndexRoute: DesignIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ConfigWorkflowsIdRoute: ConfigWorkflowsIdRoute,
  ConfigWorkflowsNewRoute: ConfigWorkflowsNewRoute,
  ExternalDocumentsTokenRoute: ExternalDocumentsTokenRoute,
  ConfigWorkflowsIndexRoute: ConfigWorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
